"""foreign key updates

Revision ID: 078ea60f75c1
Revises: 07fc70ac3fda
Create Date: 2023-08-14 10:45:53.499778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '078ea60f75c1'
down_revision = '07fc70ac3fda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voted_songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('voted_songs_user_id', 'user', ['user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voted_songs', schema=None) as batch_op:
        batch_op.drop_constraint('voted_songs_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
