"""is dj changes

Revision ID: 42a473645f5d
Revises: f0355eee2465
Create Date: 2023-09-05 13:54:34.855956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42a473645f5d'
down_revision = 'f0355eee2465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_dj', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_users', schema=None) as batch_op:
        batch_op.drop_column('is_dj')

    # ### end Alembic commands ###
