"""voted songs table

Revision ID: 5a19e557c33f
Revises: 76c4e6d2c0a8
Create Date: 2023-08-14 10:09:54.965013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a19e557c33f'
down_revision = '76c4e6d2c0a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voted_songs',
    sa.Column('vote_id', sa.Integer(), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('song_name', sa.String(length=64), nullable=True),
    sa.Column('artist_name', sa.String(length=64), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], name='voted_songs_event_id'),
    sa.PrimaryKeyConstraint('vote_id'),
    sa.UniqueConstraint('vote_id')
    )
    with op.batch_alter_table('voted_songs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voted_songs_artist_name'), ['artist_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_voted_songs_song_name'), ['song_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_voted_songs_track_id'), ['track_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voted_songs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voted_songs_track_id'))
        batch_op.drop_index(batch_op.f('ix_voted_songs_song_name'))
        batch_op.drop_index(batch_op.f('ix_voted_songs_artist_name'))

    op.drop_table('voted_songs')
    # ### end Alembic commands ###
