"""added to check if user is in event

Revision ID: 846aa3b88b67
Revises: 0afa529d1bcc
Create Date: 2023-08-11 21:53:59.216863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846aa3b88b67'
down_revision = '0afa529d1bcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_event', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('in_event')

    # ### end Alembic commands ###
