"""removed vote count again

Revision ID: 8968f4d7d0dc
Revises: b8444680d57b
Create Date: 2023-08-14 20:03:23.637474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8968f4d7d0dc'
down_revision = 'b8444680d57b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voted_songs', schema=None) as batch_op:
        batch_op.drop_column('vote_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voted_songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vote_count', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
