"""event info updates

Revision ID: f0355eee2465
Revises: f861135050a6
Create Date: 2023-08-24 21:00:45.774084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0355eee2465'
down_revision = 'f861135050a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_location', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('event_description', sa.String(length=140), nullable=True))
        batch_op.create_index(batch_op.f('ix_events_event_description'), ['event_description'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_event_location'), ['event_location'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_event_location'))
        batch_op.drop_index(batch_op.f('ix_events_event_description'))
        batch_op.drop_column('event_description')
        batch_op.drop_column('event_location')

    # ### end Alembic commands ###
